stages:
    - build
    - test


build-java:
    stage: build
    image: gradle:8.0.2-jdk17
    script:
        - echo "Compiling"
        - gradle build
    artifacts:
        paths:
            - ./build/libs/*.jar
        expire_in: 1 week

test-java:
    stage: test
    image: adoptopenjdk:17-jre-hotspot
    script:
        - echo "Testing"
        - cd ./build/libs
        - java -jar *.jar
    